name: "setup-air"
description: "A GitHub Action to set up Air."
author: "posit-pbc"
inputs:
  version:
    description: "The version of Air to use, e.g., '0.3.0'. Defaults to 'latest'."
    required: false
    default: ""
  github-token:
    description: "Used to increase the rate limit when retrieving versions and downloading Air."
    required: false
    default: ${{ github.token }}
outputs:
  air-version:
    description: "The installed Air version. Useful when using 'latest'."
runs:
  using: "node20"
  main: "dist/setup-air/index.js"
