name: "Test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-latest-version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-14, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Use latest version
        uses: ./
        with:
          args: --version
          version: latest

  test-specific-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        air-version: ["0.2.0", "0.2", "0.2.x", ">=0.2.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Use version ${{ matrix.air-version }}
        uses: ./
        with:
          args: --version
          version: ${{ matrix.air-version }}

  all-tests-passed:
    runs-on: ubuntu-latest
    needs:
      - test-latest-version
      - test-specific-version
    if: always()
    steps:
      - name: All tests passed
        run: |
          echo "All jobs passed: ${{ !contains(needs.*.result, 'failure') }}"
          # shellcheck disable=SC2242
          exit ${{ contains(needs.*.result, 'failure') && 1 || 0 }}
